### PR TITLE
Inedit mc2

### PR DESCRIPTION
**Pull request by jcelerier**
I am wondering, wouldn't it be better to put this work in a new branch ? 
Please tell me if you see anything weird. Thanks !

### CODE REVIEW

**Comment by jcelerier** [comment]
Also, the URL https://github.com/sletz/libaudiostream/compare/inedit_mc2...jcelerier:inedit_mc2?w=1 allows to see the diff without the whitespace changes.

**Comment by sletz** [comment]
OK for me, and yes better put all that new stuff on a new branch. Thanks again for the hard work !

**Comment by jcelerier** [comment]
okay, I'm putting it in a "cmake" branch

**Comment by jcelerier** [comment]
it seems that github isn't able to merge a non existing branch of a fork into the same branch in the base repo :( 

If I follow [this](http://stackoverflow.com/questions/14383212/git-pulling-a-branch-from-another-repository) correctly, doing something like this on your side should do it : 

```
cd libaudiostream
git remote add jcelerier_fork https://github.com/jcelerier/libaudiostream
git fetch jcelerier_fork 
git checkout -b cmake jcelerier_fork/cmake
git push --set-upstream origin cmake
```

**Comment by sletz** [comment]
Just done, thanks.

**Pull request closed without merging**
